DIR_MODULE_LIBFT		:= libft
DIR_INTERFACE_LIBFT	:= $(DIR_MODULE_LIBFT)
DIR_INTERNAL_LIBFT	:= $(DIR_MODULE_LIBFT)/_internal

SRC_INTERFACE_LIBFT	:= 
SRC_INTERNAL_LIBFT	:= 

OBJ_LIBFT			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_LIBFT)/, $(SRC_INTERFACE_LIBFT:.c=.o))
OBJ_LIBFT			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_LIBFT)/, $(SRC_INTERNAL_LIBFT:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_LIBFT)/%.o: $(DIR_SRC)/$(DIR_MODULE_LIBFT)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_LIBFT)/_internal -c $< -o $@
