DIR_MODULE_PROMPT		:= prompt
DIR_INTERFACE_PROMPT	:= $(DIR_MODULE_PROMPT)
DIR_INTERNAL_PROMPT	:= $(DIR_MODULE_PROMPT)/_internal

SRC_INTERFACE_PROMPT	:= prompt.c 
SRC_INTERNAL_PROMPT	:= 

OBJ_PROMPT			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PROMPT)/, $(SRC_INTERFACE_PROMPT:.c=.o))
OBJ_PROMPT			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PROMPT)/, $(SRC_INTERNAL_PROMPT:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PROMPT)/%.o: $(DIR_SRC)/$(DIR_MODULE_PROMPT)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PROMPT)/_internal -c $< -o $@
