DIR_MODULE_GLOBAL-MANAGER		:= global-manager
DIR_INTERFACE_GLOBAL-MANAGER	:= $(DIR_MODULE_GLOBAL-MANAGER)
DIR_INTERNAL_GLOBAL-MANAGER	:= $(DIR_MODULE_GLOBAL-MANAGER)/_internal

SRC_INTERFACE_GLOBAL-MANAGER	:= global-manager.c 
SRC_INTERNAL_GLOBAL-MANAGER	:= _global-manager.c 

OBJ_GLOBAL-MANAGER			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_GLOBAL-MANAGER)/, $(SRC_INTERFACE_GLOBAL-MANAGER:.c=.o))
OBJ_GLOBAL-MANAGER			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_GLOBAL-MANAGER)/, $(SRC_INTERNAL_GLOBAL-MANAGER:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_GLOBAL-MANAGER)/%.o: $(DIR_SRC)/$(DIR_MODULE_GLOBAL-MANAGER)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_GLOBAL-MANAGER)/_internal -c $< -o $@
