DIR_MODULE_PROMPTE		:= prompte
DIR_INTERFACE_PROMPTE	:= $(DIR_MODULE_PROMPTE)
DIR_INTERNAL_PROMPTE	:= $(DIR_MODULE_PROMPTE)/_internal

SRC_INTERFACE_PROMPTE	:= prompt.c 
SRC_INTERNAL_PROMPTE	:= 

OBJ_PROMPTE			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PROMPTE)/, $(SRC_INTERFACE_PROMPTE:.c=.o))
OBJ_PROMPTE			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PROMPTE)/, $(SRC_INTERNAL_PROMPTE:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PROMPTE)/%.o: $(DIR_SRC)/$(DIR_MODULE_PROMPTE)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PROMPTE)/_internal -c $< -o $@
