DIR_MODULE_SIGNAL		:= signal
DIR_INTERFACE_SIGNAL	:= $(DIR_MODULE_SIGNAL)
DIR_INTERNAL_SIGNAL	:= $(DIR_MODULE_SIGNAL)/_internal

SRC_INTERFACE_SIGNAL	:= signal.c 
SRC_INTERNAL_SIGNAL	:= 

OBJ_SIGNAL			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_SIGNAL)/, $(SRC_INTERFACE_SIGNAL:.c=.o))
OBJ_SIGNAL			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_SIGNAL)/, $(SRC_INTERNAL_SIGNAL:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_SIGNAL)/%.o: $(DIR_SRC)/$(DIR_MODULE_SIGNAL)/%.c
	@mkdir -p $(dir $@)
	@printf "\r ⚙️ $(_YELLOW) Compiling$(_RESET) %-60s" "$<"
	@$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_SIGNAL)/_internal -c $< -o $@

